version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "18:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 99
  versioning-strategy: increase
  ignore:
  - dependency-name: mobx
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.4
    - 6.1.5
    - 6.1.6
    - 6.1.7
    - 6.2.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: tslib
    versions:
    - 2.1.0
  - dependency-name: wrap-request
    versions:
    - 4.1.4
    - 4.1.5
    - 4.1.6
    - 5.0.3
    - 5.0.5
    - 5.0.8
    - 5.1.0
    - 5.1.1
